import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
// import ContactNavbar from "@/components/ContactNavbar";
import FloatingWhatsapp from "@/components/FWhatsapp";
import ContactForm from "@/components/ContactForm";

export const metadata = {
  title: "Clinic Trip",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <FloatingWhatsapp />
        {/* <ContactNavbar /> */}
        <Navbar />
        <main>{children}</main>
        <ContactForm />
        <Footer />
      </body>
    </html>
  );
}
