import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import FloatingWhatsapp from "@/components/FWhatsapp";
import ContactForm from "@/components/ContactForm";
import ScrollToTop from "@/components/ScrollToTop";

export const metadata = {
  title: "Clinic Trip",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <FloatingWhatsapp />
        <Navbar />
        <main>{children}</main>
        {/* <ContactForm /> */}
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
